-- QA Video Site: 6 projects x 10 question slots = 60 questions.
-- Safe to run on the existing project-based schema. It preserves existing question rows.

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  name text not null unique,
  display_order integer not null unique,
  created_at timestamptz not null default now()
);

insert into public.projects (name, display_order) values
  ('PRAGATI', 1),
  ('SHOONYA AVKASHA', 2),
  ('SOHAM', 3),
  ('MUKTI', 4),
  ('BHAKTI', 5),
  ('AARYA-X', 6)
on conflict (name) do update set display_order = excluded.display_order;

create table if not exists public.questions (
  id uuid primary key default gen_random_uuid(),
  project_id bigint references public.projects(id) on delete cascade,
  question_number integer,
  question text not null,
  note text default '',
  video_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.questions add column if not exists project_id bigint;
alter table public.questions add column if not exists question_number integer;
alter table public.questions add column if not exists updated_at timestamptz not null default now();

-- If an older deployment already has questions without project assignments,
-- place the first 10 legacy rows into PRAGATI rather than deleting them.
with numbered as (
  select q.id, row_number() over (order by q.created_at, q.id) as rn
  from public.questions q
  where q.project_id is null
)
update public.questions q
set project_id = (select id from public.projects where display_order = 1),
    question_number = numbered.rn::integer
from numbered
where q.id = numbered.id and numbered.rn <= 10;

-- Any legacy rows beyond 10 are left untouched rather than silently losing data.

alter table public.questions
  drop constraint if exists questions_project_question_number_key;

alter table public.questions
  add constraint questions_project_question_number_key unique (project_id, question_number);

alter table public.questions
  drop constraint if exists questions_question_number_check;

alter table public.questions
  add constraint questions_question_number_check check (question_number between 1 and 10);

alter table public.questions
  drop constraint if exists questions_project_id_fkey;

alter table public.questions
  add constraint questions_project_id_fkey foreign key (project_id) references public.projects(id) on delete cascade;

create index if not exists questions_project_id_idx on public.questions(project_id);

create or replace function public.set_questions_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists questions_updated_at on public.questions;
create trigger questions_updated_at
before update on public.questions
for each row execute function public.set_questions_updated_at();

-- Storage bucket. The backend also checks/creates this at startup.
insert into storage.buckets (id, name, public)
values ('qa-videos', 'qa-videos', true)
on conflict (id) do update set public = true;
